### ISSUE TITLE
Feedback on Example 2.1.1 in Row Reduction

### ISSUE THREAD

**Issue by SportsSciGuy** [QBobWatson/gt-linalg#253] opened 2019-03-24 20:41 UTC
In reference to version 5f9d00240bebd633057eaab6b1d13c8707d3fd73

On the 2nd and 3rd steps after forming the Augmented matrix you have the manipulation being performed listed as swapping Row₂ and Row₃ but based on the change made to Row₃ it looks like that is not the manipulation performed.  

Thanks for this amazing book though, I love it.

**Comment by QBobWatson** [comment] 2019-03-25 15:28
Duplicate of #250.  We're holding off publishing the latest version until after classes end here, since the chapters got re-numbered.  Thanks for catching this!

**Closed by QBobWatson** 2019-03-25 15:28 UTC
